name: Building spring boot app

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and deploy spring app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build the docker Image
        uses: docker/build-push-action@v2
        with: &dockerize
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/demo.jar:today

      - name: Login to Dockerfile
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push To Docker Hub
        uses: docker/build-push-action@v2
        with:
          <<: *dockerize
          push: true






          


